name: Daily Commit Automation

on:
  schedule:
    - cron: '30 2 * * *'  # Runs daily at 02:30 UTC

jobs:
  commit-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "23f2001216@ds.study.iitm.ac.in"

      - name: Create a commit
        run: |
          echo "Last run: $(date)" > last_run.txt
          git add last_run.txt
          git commit -m "Automated commit on $(date)"
          git push
