name: Daily Automated Commit

on:
  schedule:
    # Run at 02:30 UTC every day
    - cron: '30 2 * * *'
  workflow_dispatch:

jobs:
  create-daily-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: 23f2001216@ds.study.iitm.ac.in  # Email as step name
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          echo "Daily update: $(date)" >> daily-status.txt
          git add daily-status.txt
          git commit -m "Daily automated update $(date)"
          git push
