name: "Daily Commit Automation by 23f2001216@ds.study.iitm.ac.in"

on:
  schedule:
    - cron: "30 2 * * *"  # Runs daily at 2:30 AM UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  daily-commit:
    name: "Commit Job by 23f2001216@ds.study.iitm.ac.in"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Repository by 23f2001216@ds.study.iitm.ac.in"
        uses: actions/checkout@v4

      - name: "Step executed by 23f2001216@ds.study.iitm.ac.in"
        run: |
          echo "Last update: $(date)" > last_update.txt
          git config --global user.name "github-actions[bot]"
          git config --global user.email "23f2001216@ds.study.iitm.ac.in"
          git add last_update.txt
          git commit -m "Automated update: $(date)"
          git push
