name: Daily Commit Workflow

on:
  schedule:
    - cron: '10 17 * * *' 
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add commit using 23f2001216@ds.study.iitm.ac.in
        env:
          PAT: ${{ secrets.PAT }}  # PAT stored as a secret
        run: |
          git config --global user.name "Aryan"
          git config --global user.email "23f2001216@ds.study.iitm.ac.in"

          echo "Daily commit on $(date)" >> daily-log.txt

          git add daily-log.txt
          git commit -m "Automated daily commit on $(date)"

          # Debugging steps BEFORE the push
          ls -la
          git status

          git push origin main  # or your main branch name, using the PAT for auth
          git push "https://${{ secrets.PAT }}@github.com/${{ github.repository }}.git" main
